services:
  frontend:
    build:
      context: frontend
      dockerfile: ./Dockerfile
    env_file: frontend/.env
    ports:
      - 127.0.0.1:5173:5173
  backend:
    build:
      context: backend
      dockerfile: ./Dockerfile
    env_file: backend/.env
    ports:
      - 127.0.0.1:8080:8080
